### ISSUE TITLE
ExpressLRS Configurator opens with an empty windows

### ISSUE THREAD

**Issue by H4mmerstein** [ExpressLRS/ExpressLRS-Configurator#611] opened 2024-06-01 14:04 UTC
## Expected Behavior

The ExpressLRS Configurator starts normally.

## Current Behavior

The ExpressLRS Configurator starts with an empty window.

## Steps to Reproduce

1. Install ExpressLRS Configurator (for all or only for local user, does not matter).

2. Start ExpressLRS Configurator.

## Context

I tried restarting my machine.
I tried reinstalling ExpressLRS Configurator multiple times (for current user and for all users).
I checked my firewall and antivirus (both Windows Defender).
I tried installing version 1.6.0. It had the same behaviour. At least it showed me an update dialog which I used to update to 1.6.1 but afterwards the issue persisted.
Same with version 1.5.9.
I am a software developer and would be glad to provide help to solve this issue. If you need logs or something, let me know.

## Your Environment

- Operating System and version: Windows 11
- TX hardware: Radiomaster Boxer (internal ELRS)
- ExpressLRS Configurator 1.6.1

**Comment by jurgelenas** [comment] 2024-06-15 19:32
Hey @H4mmerstein 

Can you test latest nightly release? https://github.com/ExpressLRS/ExpressLRS-Configurator-Nightlies/releases

**Comment by jurgelenas** [comment] 2024-06-15 20:48
Since I can not reproduce this I will be closing the issue.

**Closed by jurgelenas** 2024-06-15 20:48 UTC
Labels: bug

**Comment by H4mmerstein** [comment] 2024-06-17 19:49
Hey @jurgelenas , thanks for your help. The latest nightly release did actually work! Thank you very much!
