### ISSUE TITLE
[1.3.4] There is no Jumper 2.4 GHz AION Nano TX Module

### ISSUE THREAD

**Issue by hi6otb** [ExpressLRS/ExpressLRS-Configurator#241] opened 2022-01-25 01:01 UTC
## Expected Behavior

I want to update Jumper 2.4 GHz AION Nano TX Module .

## Current Behavior

I updated configurator to 1.3.4 but there is no Jumper 2.4 GHz AION Nano TX Module on Device tab.

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

I use windows env.

- Operating System and version:
- TX hardware: Jumper 2.4 GHz AION Nano TX Module
- RX hardware:
<img width="862" alt="キャプチャ" src="https://user-images.githubusercontent.com/46843043/150890908-0acfb61e-5ce9-4e3f-94ef-1c823c23c406.PNG">

**Comment by pkendall64** [comment] 2022-01-25 01:37
It's coming! We've had to work through a few issues with this device.

**Comment by jurgelenas** [comment] 2022-01-25 06:05
There is no official release that supports Jumper aion tx yet. Please use git master branch. 

Closing since this is not a bug.

**Closed by jurgelenas** 2022-01-25 06:05 UTC
Labels: bug

**Comment by pkendall64** [comment] 2022-01-25 06:12
Actually, please flash PR #1335 "Serial pin checking" until that is merged into master.
