### ISSUE TITLE
Cloud build on Ubuntu 22.04

### ISSUE THREAD

**Issue by freasy** [ExpressLRS/ExpressLRS-Configurator#520] opened 2023-06-14 08:35 UTC
I just installed 1.6.0-RC1 on Ubuntu 22.04 and wanted to flash 3.3.0-RC1 on a BetaFPV SuperD RX, but i get this error

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code

    exec(code, run_globals)
  File "/home/eike/.config/ExpressLRS Configurator/firmwares/cloud/ExpressLRS/079a91d3db39b64ea39bccd25f9bf4457659152d/firmware/flasher.pyz/__main__.py", line 3, in <module>
    if __name__ == '__main__':
  File "/home/eike/.config/ExpressLRS Configurator/firmwares/cloud/ExpressLRS/079a91d3db39b64ea39bccd25f9bf4457659152d/firmware/flasher.pyz/_bootstrap/__init__.py", line 253, in bootstrap
  File "/home/eike/.config/ExpressLRS Configurator/firmwares/cloud/ExpressLRS/079a91d3db39b64ea39bccd25f9bf4457659152d/firmware/flasher.pyz/_bootstrap/__init__.py", line 81, in import_string
  File "/home/eike/.config/ExpressLRS Configurator/firmwares/cloud/ExpressLRS/079a91d3db39b64ea39bccd25f9bf4457659152d/firmware/flasher.pyz/_bootstrap/__init__.py", line 59, in import_string
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/eike/.shiv/flasher.pyz_a172ac6becb894df4b3b5c405efe26698f46dde65672ce402236f12100c737ef/site-packages/binary_configurator.py", line 17, in <module>
    import binary_flash
  File "/home/eike/.shiv/flasher.pyz_a172ac6becb894df4b3b5c405efe26698f46dde65672ce402236f12100c737ef/site-packages/binary_flash.py", line 19, in <module>
    from external.esptool import esptool
  File "/home/eike/.shiv/flasher.pyz_a172ac6becb894df4b3b5c405efe26698f46dde65672ce402236f12100c737ef/site-packages/external/esptool/esptool/__init__.py", line 42, in <module>
    from esptool.cmds import (
ModuleNotFoundError: No module named 'esptool.cmds'; 'esptool' is not a package
```

## Expected Behavior

Able to flash

## Current Behavior

Cloud build not working

## Steps to Reproduce

1. Remove `~/.config/ExpressLRS Configurator` folder (or rename)

2. Remove `~/.shiv/flasher.pyz_<hash>` folder

3. Start 1.6.0-RC1 configurator

4. Select BetaFPV SuperD Rx

5. Hit flash

## Your Environment

- Operating System and version: Ubuntu 22.04
- TX hardware: DIY 2.4 E28
- RX hardware: BetaFPV SuperD 2.4

**Comment by jurgelenas** [comment] 2023-06-21 08:26
I am sorry but I am not able to reproduce this issue. I am working in an environment exactly like yours.

**Comment by jurgelenas** [comment] 2023-06-26 10:11
We did lots of testing internally and we were not able to reproduce this issue.

We have tried it on the existing OSes and even the ones installed from scratch. Everything worked as expected.

I am closing the issue for now, please let me know if you want to work on debugging this.

**Closed by jurgelenas** 2023-06-26 10:11 UTC
Labels: bug
